"""Rajasthan sarkari exams ki built-in list aur seed MCQs.

Pattern notes coaching-summary NAHI, balki 'badal sakta hai' wala disclaimer
ke saath hain. Vacancy / cutoff / exam date yahan hardcode nahi — wo official
PDF se aani chahiye.
"""

from __future__ import annotations

SUBS_CORE = [
    ["gk", "राजस्थान GK"],
    ["his", "इतिहास"],
    ["geo", "भूगोल"],
    ["pol", "राजव्यवस्था"],
    ["hin", "हिंदी"],
    ["rea", "रीजनिंग"],
    ["sci", "विज्ञान"],
    ["com", "कम्प्यूटर"],
]
SUBS_REET = SUBS_CORE + [["cdp", "बाल विकास"], ["san", "संस्कृत"], ["eng", "अंग्रेज़ी"]]
SUBS_RAS = SUBS_CORE + [["cur", "करेंट अफेयर्स"], ["eng", "अंग्रेज़ी"]]

DISCLAIMER = (
    "यह सामान्य तैयारी-नोट है, आधिकारिक अधिसूचना नहीं। "
    "अंक, समय और चरण बदल सकते हैं — सिलेबस PDF ही अंतिम मानी जाए।"
)


def E(
    slug: str,
    name_hi: str,
    name_en: str,
    category: str,
    body: str,
    official_url: str,
    keywords: list[str],
    aliases: list[str],
    description_hi: str = "",
    pattern_hi: str = "",
    subjects: list | None = None,
) -> dict:
    return {
        "slug": slug,
        "name_hi": name_hi,
        "name_en": name_en,
        "category": category,
        "body": body,
        "official_url": official_url,
        "keywords": keywords,
        "aliases": aliases + [slug, name_en.lower(), name_hi.lower()],
        "description_hi": description_hi,
        "pattern_hi": pattern_hi or DISCLAIMER,
        "subjects": subjects or SUBS_CORE,
    }


RPSC = "https://rpsc.rajasthan.gov.in/"
RSSB = "https://rsmssb.rajasthan.gov.in/"
POLICE = "https://police.rajasthan.gov.in/"
HCRAJ = "https://hcraj.nic.in/"
WCD = "https://wcd.rajasthan.gov.in/"
FOREST = "https://forest.rajasthan.gov.in/"
EDU = "https://education.rajasthan.gov.in/"
HEALTH = "https://rajswasthya.rajasthan.gov.in/"
DTE = "https://dte.rajasthan.gov.in/"
UNIRAJ = "https://www.uniraj.ac.in/"
PANJIYAN = "https://panjiyan.rajasthan.gov.in/"
RBSE = "https://rajeduboard.rajasthan.gov.in/"

EXAMS: list[dict] = [
    E(
        "ras-pre",
        "RAS / RTS प्रारंभिक",
        "RAS RTS Prelims",
        "RPSC",
        "RPSC",
        RPSC,
        ["ras prelims", "ras pre", "rts prelims", "combined competitive", "राज्य एवं अधीनस्थ"],
        ["ras", "आरएएस", "rts", "आरटीएस", "ras pre", "ras prelims", "prelims"],
        "Rajasthan State and Subordinate Services Combined Competitive Examination — Prelims.",
        "आमतौर पर वस्तुनिष्ठ प्रारंभिक परीक्षा, फिर मुख्य और साक्षात्कार। 2026 चक्र में सिलेबस बदला बताया गया है — केवल RPSC की सिलेबस PDF मानें। " + DISCLAIMER,
        SUBS_RAS,
    ),
    E(
        "ras-mains",
        "RAS / RTS मुख्य परीक्षा",
        "RAS RTS Mains",
        "RPSC",
        "RPSC",
        RPSC,
        ["ras mains", "rts mains", "मुख्य परीक्षा ras"],
        ["ras mains", "आरएएस मेन्स", "mains"],
        "RAS/RTS की वर्णनात्मक मुख्य परीक्षा।",
        "मुख्य परीक्षा वर्णनात्मक होती है। पत्रों की संख्या और अंक आधिकारिक सिलेबस से मिलाएँ। " + DISCLAIMER,
        SUBS_RAS,
    ),
    E(
        "school-lecturer",
        "स्कूल व्याख्याता (Grade-I)",
        "School Lecturer",
        "RPSC",
        "RPSC",
        RPSC,
        ["school lecturer", "स्कूल व्याख्याता", "first grade teacher", "lecturer school"],
        ["school lecturer", "व्याख्याता", "lecturer", "grade 1 teacher", "first grade"],
        "स्कूल शिक्षा विभाग के व्याख्याता पद — आमतौर पर RPSC।",
        "विषय-पत्र + सामान्य ज्ञान का पैटर्न विज्ञापन के साथ आता है। " + DISCLAIMER,
    ),
    E(
        "college-lecturer",
        "कॉलेज व्याख्याता / सहायक आचार्य",
        "College Lecturer",
        "RPSC",
        "RPSC",
        RPSC,
        ["college lecturer", "assistant professor", "सहायक आचार्य", "कॉलेज व्याख्याता"],
        ["college lecturer", "assistant professor", "सहायक आचार्य"],
        "महाविद्यालय शिक्षा — RPSC।",
        "विषय के अनुसार पत्र अलग होते हैं। आधिकारिक सिलेबस देखें। " + DISCLAIMER,
    ),
    E(
        "aen",
        "सहायक अभियंता (AEn)",
        "Assistant Engineer",
        "RPSC",
        "RPSC",
        RPSC,
        ["assistant engineer", "aen", "सहायक अभियंता"],
        ["aen", "ae", "assistant engineer", "सहायक अभियंता"],
        "AEn भर्ती अक्सर RPSC के माध्यम से। विभाग विज्ञापन से पुष्टि करें।",
        "तकनीकी पत्र + सामान्य अध्ययन। शाखा (Civil/Mechanical/Electrical) विज्ञापन में देखें। " + DISCLAIMER,
    ),
    E(
        "so-stat",
        "सांख्यिकी अधिकारी",
        "Statistical Officer",
        "RPSC",
        "RPSC",
        RPSC,
        ["statistical officer", "सांख्यिकी अधिकारी", "statistics officer"],
        ["so", "statistical officer", "सांख्यिकी"],
        "Statistical Officer — RPSC।",
        "सांख्यिकी + सामान्य ज्ञान। विस्तृत पत्र आधिकारिक सिलेबस में। " + DISCLAIMER,
    ),
    E(
        "si-police",
        "पुलिस सब-इंस्पेक्टर / प्लाटून कमांडर",
        "Police SI Platoon Commander",
        "RPSC / Police",
        "RPSC",
        RPSC,
        ["sub-inspector", "platoon commander", "सब इंस्पेक्टर", "प्लाटून कमांडर", "police si"],
        ["si", "sub inspector", "प्लाटून", "platoon", "police si", "दारोगा"],
        "SI / Platoon Commander भर्ती का आयोजक चक्र के अनुसार RPSC या पुलिस विभाग हो सकता है। दोनों आधिकारिक साइट देखें।",
        "लिखित परीक्षा के बाद PST/PET और मेडिकल हो सकता है। " + DISCLAIMER,
        SUBS_CORE,
    ),
    E(
        "patwari",
        "पटवारी",
        "Patwari",
        "RSSB",
        "RSSB / RSMSSB",
        RSSB,
        ["patwari", "पटवारी", "patwari bharti"],
        ["patwari", "पटवारी", "पटवार"],
        "राजस्व विभाग — पटवारी, आयोजक RSSB (पुराना नाम RSMSSB)।",
        "कई चक्रों में लगभग 150 प्रश्न / 300 अंक वाला वस्तुनिष्ठ पत्र देखा गया है (राजस्थान GK, भारत GK, हिंदी-अंग्रेज़ी, रीजनिंग, गणित, कम्प्यूटर)। नया विज्ञापन ही मान्य है। " + DISCLAIMER,
    ),
    E(
        "ldc",
        "LDC / जूनियर सहायक",
        "Lower Division Clerk",
        "RSSB",
        "RSSB",
        RSSB,
        ["lower division clerk", "junior assistant", "ldc", "जूनियर सहायक", "क्लर्क"],
        ["ldc", "clerk", "जूनियर सहायक", "lower division"],
        "लिपिक संवर्ग। कई भर्तियों में CET अर्हता जुड़ी रही है — विज्ञापन पढ़ें।",
        "लिखित + टाइपिंग / कम्प्यूटर टेस्ट हो सकता है। " + DISCLAIMER,
    ),
    E(
        "vdo",
        "ग्राम विकास अधिकारी (VDO)",
        "Village Development Officer",
        "RSSB",
        "RSSB",
        RSSB,
        ["village development officer", "gram vikas adhikari", "vdo", "ग्राम विकास अधिकारी"],
        ["vdo", "gram sevak", "ग्राम सेवक", "gva"],
        "पंचायती राज / ग्राम विकास अधिकारी।",
        "प्रारंभिक वस्तुनिष्ठ पत्र। मुख्य परीक्षा वाले चक्र भी रहे हैं — सिलेबस PDF देखें। " + DISCLAIMER,
    ),
    E(
        "cet-grad",
        "CET स्नातक",
        "CET Graduation",
        "RSSB",
        "RSSB",
        RSSB,
        ["common eligibility test", "cet graduation", "cet degree", "सीईटी स्नातक"],
        ["cet", "सीईटी", "cet grad", "cet graduation", "common eligibility"],
        "RSSB Common Eligibility Test — स्नातक स्तर। कई भर्तियों की अर्हता परीक्षा।",
        "स्तर (12वीं / स्नातक) विज्ञापन में अलग होता है। " + DISCLAIMER,
        SUBS_RAS,
    ),
    E(
        "cet-12",
        "CET 12वीं",
        "CET Senior Secondary",
        "RSSB",
        "RSSB",
        RSSB,
        ["cet 12", "cet senior secondary", "सीईटी 12", "cet 10+2"],
        ["cet 12", "cet 12th", "12th cet", "सीईटी बारह"],
        "RSSB CET — सीनियर सेकेंडरी स्तर।",
        DISCLAIMER,
    ),
    E(
        "jr-accountant",
        "कनिष्ठ लेखाकार",
        "Junior Accountant",
        "RSSB",
        "RSSB",
        RSSB,
        ["junior accountant", "कनिष्ठ लेखाकार", "jr accountant"],
        ["junior accountant", "लेखाकार", "accountant"],
        "RSSB कनिष्ठ लेखाकार।",
        "लेखांकन + सामान्य ज्ञान / हिंदी। " + DISCLAIMER,
    ),
    E(
        "agri-supervisor",
        "कृषि पर्यवेक्षक",
        "Agriculture Supervisor",
        "RSSB",
        "RSSB",
        RSSB,
        ["agriculture supervisor", "कृषि पर्यवेक्षक", "agri supervisor"],
        ["agri", "agriculture supervisor", "कृषि"],
        "कृषि विभाग — अक्सर RSSB।",
        "कृषि विषय + सामान्य ज्ञान। " + DISCLAIMER,
    ),
    E(
        "librarian",
        "पुस्तकालयाध्यक्ष ग्रेड-III",
        "Librarian Grade III",
        "RSSB",
        "RSSB",
        RSSB,
        ["librarian", "पुस्तकालयाध्यक्ष", "library grade"],
        ["librarian", "लाइब्रेरियन", "पुस्तकालय"],
        "लाइब्रेरियन ग्रेड-III।",
        "पुस्तकालय विज्ञान + सामान्य पत्र। " + DISCLAIMER,
    ),
    E(
        "lab-assistant",
        "प्रयोगशाला सहायक",
        "Lab Assistant",
        "RSSB",
        "RSSB",
        RSSB,
        ["lab assistant", "प्रयोगशाला सहायक", "laboratory assistant"],
        ["lab assistant", "लैब असिस्टेंट", "lab"],
        "स्कूल शिक्षा — लैब असिस्टेंट, अक्सर RSSB।",
        "विज्ञान / विषय समूह विज्ञापन के अनुसार। " + DISCLAIMER,
    ),
    E(
        "mahila-supervisor",
        "महिला पर्यवेक्षक",
        "Mahila Supervisor",
        "RSSB / WCD",
        "RSSB",
        RSSB,
        ["mahila supervisor", "महिला पर्यवेक्षक", "women supervisor", "wcd supervisor"],
        ["mahila", "महिला पर्यवेक्षक", "supervisor wcd"],
        "महिला एवं बाल विकास से जुड़ा पर्यवेक्षक पद। आयोजक RSSB रहा है।",
        DISCLAIMER,
    ),
    E(
        "constable",
        "राजस्थान पुलिस कांस्टेबल",
        "Rajasthan Police Constable",
        "Police / RSSB",
        "Rajasthan Police / RSSB",
        POLICE,
        ["police constable", "कांस्टेबल", "constable bharti", "raj police constable"],
        ["constable", "कांस्टेबल", "police constable", "sipahi"],
        "कांस्टेबल भर्ती पुलिस विभाग या RSSB — उस वर्ष के विज्ञापन से देखें।",
        "लिखित + PST/PET + मेडिकल आम रहा है। " + DISCLAIMER,
    ),
    E(
        "reet-l1",
        "REET स्तर-1",
        "REET Level 1",
        "REET",
        "RSSB / RBSE",
        RSSB,
        ["reet level 1", "reet level-i", "रीट लेवल 1", "primary teacher eligibility"],
        ["reet", "रीट", "reet 1", "reet l1", "level 1"],
        "राजस्थान अध्यापक पात्रता परीक्षा, स्तर-1 (कक्षा 1-5)। आयोजक पहले RBSE, बाद में RSSB रहा है।",
        "बाल विकास, हिंदी, अंग्रेज़ी, गणित, पर्यावरण अध्ययन — आधिकारिक सिलेबस से अंक मिलाएँ। " + DISCLAIMER,
        SUBS_REET,
    ),
    E(
        "reet-l2",
        "REET स्तर-2",
        "REET Level 2",
        "REET",
        "RSSB / RBSE",
        RSSB,
        ["reet level 2", "reet level-ii", "रीट लेवल 2"],
        ["reet 2", "reet l2", "level 2", "reet level 2"],
        "REET स्तर-2 (कक्षा 6-8)।",
        "भाषा, CDP, और विषय समूह (गणित-विज्ञान / सामाजिक / संस्कृत आदि)। " + DISCLAIMER,
        SUBS_REET,
    ),
    E(
        "grade3",
        "अध्यापक ग्रेड-3 / तृतीय श्रेणी",
        "Third Grade Teacher",
        "RSSB",
        "RSSB",
        RSSB,
        ["third grade teacher", "grade 3 teacher", "तृतीय श्रेणी शिक्षक", "3rd grade"],
        ["3rd grade", "third grade", "grade 3", "ग्रेड 3", "तृतीय"],
        "तृतीय श्रेणी शिक्षक भर्ती। REET पात्रता अक्सर शर्त रहती है — विज्ञापन पढ़ें।",
        DISCLAIMER,
        SUBS_REET,
    ),
    E(
        "grade2",
        "अध्यापक ग्रेड-2 / द्वितीय श्रेणी",
        "Second Grade Teacher",
        "RSSB / RPSC",
        "RSSB / RPSC",
        RSSB,
        ["second grade teacher", "grade 2 teacher", "द्वितीय श्रेणी", "adhyapak grade ii", "वरिष्ठ अध्यापक"],
        ["grade 2", "2nd grade", "ग्रेड 2", "वरिष्ठ अध्यापक", "adhyapak"],
        "द्वितीय श्रेणी / वरिष्ठ अध्यापक। आयोजक चक्र के अनुसार RSSB या RPSC हो सकता है — विज्ञापन देखें।",
        DISCLAIMER,
        SUBS_REET,
    ),
    E(
        "jen",
        "कनिष्ठ अभियंता (JEn)",
        "Junior Engineer",
        "RSSB",
        "RSSB",
        RSSB,
        ["junior engineer", "jen", "कनिष्ठ अभियंता"],
        ["jen", "je", "junior engineer", "कनिष्ठ अभियंता"],
        "JEn (सिविल / मैकेनिकल / इलेक्ट्रिकल) अक्सर RSSB। कुछ विभाग RPSC से भी निकालते हैं।",
        "डिप्लोमा/डिग्री शाखा के अनुसार पत्र। " + DISCLAIMER,
    ),
    E(
        "hc-ldc",
        "उच्च न्यायालय LDC / जूनियर असिस्टेंट",
        "Rajasthan High Court LDC",
        "High Court",
        "Rajasthan High Court",
        HCRAJ,
        ["high court ldc", "hc ldc", "junior assistant high court", "clerk grade-ii"],
        ["hc ldc", "high court ldc", "हाईकोर्ट एलडीसी", "hc clerk"],
        "राजस्थान उच्च न्यायालय, जोधपुर — लिपिक संवर्ग। CET जरूरी है या नहीं, विज्ञापन में लिखा होगा।",
        "लिखित + टाइपिंग आम है। " + DISCLAIMER,
    ),
    E(
        "hc-jja",
        "जूनियर ज्यूडिशियल असिस्टेंट (JJA)",
        "Junior Judicial Assistant",
        "High Court",
        "Rajasthan High Court",
        HCRAJ,
        ["junior judicial assistant", "jja", "जूनियर ज्यूडिशियल"],
        ["jja", "judicial assistant", "जजा"],
        "Rajasthan High Court JJA।",
        DISCLAIMER,
    ),
    E(
        "hc-steno",
        "उच्च न्यायालय स्टेनोग्राफर",
        "High Court Stenographer",
        "High Court",
        "Rajasthan High Court",
        HCRAJ,
        ["stenographer high court", "hc steno", "स्टेनोग्राफर"],
        ["steno", "stenographer", "आशुलिपिक"],
        "स्टेनोग्राफर — हाई कोर्ट।",
        "शॉर्टहैंड और टाइपिंग टेस्ट अपेक्षित। " + DISCLAIMER,
    ),
    E(
        "forest-guard",
        "वनरक्षक",
        "Forest Guard",
        "Forest",
        "RSSB / Forest",
        RSSB,
        ["forest guard", "vanrakshak", "वनरक्षक", "van rakshak"],
        ["vanrakshak", "वनरक्षक", "forest guard", "vanrakshak exam"],
        "वनरक्षक भर्ती हाल के चक्रों में RSSB के जरिए हुई है। वन विभाग की साइट भी देखें।",
        "लिखित के बाद PST/PET हो सकता है। " + DISCLAIMER,
    ),
    E(
        "forester",
        "वनपाल (Forester)",
        "Forester",
        "Forest",
        "RSSB / Forest",
        RSSB,
        ["forester", "vanpal", "वनपाल"],
        ["forester", "वनपाल", "vanpal"],
        "वनपाल / Forester।",
        DISCLAIMER,
    ),
    E(
        "bstc",
        "BSTC / Pre-D.El.Ed",
        "BSTC Pre DElEd",
        "Education",
        "Elementary Education",
        PANJIYAN,
        ["bstc", "pre d.el.ed", "pre-deled", "डीएलएड प्रवेश"],
        ["bstc", "बीएसटीसी", "pre deled", "d.el.ed", "deled"],
        "प्राथमिक शिक्षा में द्विवर्षीय पाठ्यक्रम का प्रवेश। पोर्टल बदल सकता है — panjiyan / शिक्षा विभाग जाँचें।",
        "प्रवेश परीक्षा का पैटर्न उस वर्ष की सूचना-पुस्तिका में होता है। " + DISCLAIMER,
        SUBS_REET,
    ),
    E(
        "nursing",
        "नर्सिंग ऑफिसर / GNM भर्ती",
        "Nursing Officer GNM",
        "Health",
        "Health / RSSB",
        HEALTH,
        ["nursing officer", "gnm recruitment", "नर्सिंग अधिकारी", "staff nurse"],
        ["gnm", "nursing", "नर्सिंग", "staff nurse", "nurse"],
        "GNM / B.Sc नर्सिंग भर्ती स्वास्थ्य विभाग या RSSB। पाठ्यक्रम प्रवेश के लिए rajgnm पोर्टल अलग है।",
        "नर्सिंग विषय + राजस्थान GK। " + DISCLAIMER,
    ),
    E(
        "anm",
        "ANM / महिला स्वास्थ्य कार्यकर्ता",
        "ANM",
        "Health",
        "Health / RSSB",
        HEALTH,
        ["auxiliary nurse midwife", "anm", "महिला स्वास्थ्य कार्यकर्ता"],
        ["anm", "एएनएम", "health worker"],
        "ANM भर्ती।",
        DISCLAIMER,
    ),
    E(
        "iti",
        "ITI प्रशिक्षक / ITI परीक्षा",
        "ITI Rajasthan",
        "Technical",
        "DTE / RSSB",
        DTE,
        ["iti instructor", "iti rajasthan", "औद्योगिक प्रशिक्षण"],
        ["iti", "आईटीआई", "instructor iti"],
        "ITI प्रशिक्षक भर्ती RSSB/DTE हो सकती है। ट्रेड परीक्षा परिणाम DTE / NCVT पर।",
        DISCLAIMER,
    ),
    E(
        "anganwadi",
        "आंगनवाड़ी कार्यकर्ता / सहायिका",
        "Anganwadi Worker",
        "WCD",
        "WCD / RSSB",
        WCD,
        ["anganwadi", "आंगनवाड़ी", "anganwadi worker", "anganwadi helper"],
        ["anganwadi", "आंगनवाड़ी", "aanganwadi", "karyakarta"],
        "आंगनवाड़ी भर्ती WCD या RSSB। आधिकारिक विज्ञापन के बिना आवेदन लिंक पर भरोसा न करें।",
        DISCLAIMER,
    ),
    E(
        "uniraj",
        "राजस्थान विश्वविद्यालय परीक्षा",
        "University of Rajasthan",
        "University",
        "University of Rajasthan",
        UNIRAJ,
        ["uniraj", "university of rajasthan", "राजस्थान विश्वविद्यालय"],
        ["uniraj", "यूनिराज", "university exam", "ru exam"],
        "कोर्स परीक्षा, प्रवेश और परिणाम — uniraj.ac.in। कॉलेज-स्तरीय दूसरे विश्वविद्यालय अपनी साइट पर देखें।",
        "पाठ्यक्रम विभाग / पेपर कोड के अनुसार होता है। " + DISCLAIMER,
        SUBS_RAS,
    ),
    E(
        "raj-gk",
        "राजस्थान GK अभ्यास",
        "Rajasthan GK Practice",
        "Practice",
        "Practice bank",
        RPSC,
        ["rajasthan gk practice", "राजस्थान सामान्य ज्ञान अभ्यास"],
        ["gk practice", "राज gk practice"],
        "किसी एक भर्ती से बँधा नहीं। राजस्थान GK और स्थिर तथ्यों का अभ्यास। करेंट अफेयर्स के लिए AI से पूछें और आधिकारिक स्रोत मिलाएँ।",
        "यह भर्ती नहीं, अभ्यास-श्रेणी है।",
        SUBS_RAS,
    ),
]

PORTALS = [
    {"url": RPSC, "note": "RPSC homepage", "exam_slug": None},
    {"url": RSSB, "note": "RSSB / RSMSSB homepage", "exam_slug": None},
    {"url": "https://rssb.rajasthan.gov.in/", "note": "RSSB alternate host", "exam_slug": None},
    {"url": POLICE, "note": "Rajasthan Police", "exam_slug": "constable"},
    {"url": HCRAJ, "note": "High Court", "exam_slug": None},
    {"url": WCD, "note": "Women and Child Development", "exam_slug": "anganwadi"},
    {"url": FOREST, "note": "Forest department", "exam_slug": "forest-guard"},
    {"url": EDU, "note": "Education department", "exam_slug": None},
    {"url": "https://recruitment.rajasthan.gov.in/", "note": "Recruitment portal", "exam_slug": None},
    {"url": RBSE, "note": "RBSE", "exam_slug": "reet-l1"},
    {"url": HEALTH, "note": "Health department", "exam_slug": "nursing"},
    {"url": "https://rajgnm.rajasthan.gov.in/", "note": "GNM admission", "exam_slug": "nursing"},
    {"url": "https://hte.rajasthan.gov.in/", "note": "Higher / technical education", "exam_slug": "iti"},
    {"url": DTE, "note": "DTE", "exam_slug": "iti"},
    {"url": PANJIYAN, "note": "Panjiyan / BSTC related", "exam_slug": "bstc"},
    {"url": UNIRAJ, "note": "University of Rajasthan", "exam_slug": "uniraj"},
]


def Q(question, options, answer_index, explanation, topic="rajasthan gk", tags=None, difficulty="easy"):
    return {
        "question": question,
        "options": options,
        "answer_index": answer_index,
        "explanation": explanation,
        "topic": topic,
        "tags": tags or [topic, "rajasthan gk"],
        "difficulty": difficulty,
        "exam_id": None,
        "source": "seed",
    }


# answer_index 0-based. Facts are standard textbook items, not current vacancies.
SEED_MCQS = [
    Q(
        "राजस्थान दिवस कब मनाया जाता है?",
        ["18 मार्च", "30 मार्च", "1 नवम्बर", "26 जनवरी"],
        1,
        "30 मार्च 1949 को वृहत्तर राजस्थान बना था। इसी दिन राजस्थान दिवस मनाया जाता है। 1 नवम्बर 1956 को राज्य पुनर्गठन के बाद वर्तमान स्वरूप बना।",
        tags=["rajasthan gk", "itihas", "pol"],
    ),
    Q(
        "मत्स्य संघ का गठन कब हुआ था?",
        ["17 मार्च 1948", "18 मार्च 1948", "25 मार्च 1948", "30 मार्च 1949"],
        1,
        "मत्स्य संघ 18 मार्च 1948 को बना। इसमें अलवर, भरतपुर, धौलपुर और करौली थे। राजधानी अलवर थी। यह 15 मई 1949 को वृहत्तर राजस्थान में मिला।",
        topic="itihas",
        tags=["itihas", "rajasthan gk", "matsya"],
        difficulty="medium",
    ),
    Q(
        "मत्स्य संघ की राजधानी कहाँ थी?",
        ["भरतपुर", "धौलपुर", "अलवर", "करौली"],
        2,
        "मत्स्य संघ की राजधानी अलवर थी। राजप्रमुख धौलपुर के महाराजा थे — यह अक्सर उलझाया जाने वाला तथ्य है।",
        topic="itihas",
        tags=["itihas", "rajasthan gk"],
        difficulty="medium",
    ),
    Q(
        "राजस्थान का राज्य पक्षी कौन सा है?",
        ["मोर", "सारस", "गोडावण", "तोता"],
        2,
        "गोडावण (Great Indian Bustard) राजस्थान का राज्य पक्षी है। यह खासकर थार क्षेत्र में पाया जाता है और संकटग्रस्त है।",
        tags=["rajasthan gk", "geo"],
    ),
    Q(
        "राजस्थान का राज्य वृक्ष कौन सा है?",
        ["रोहिड़ा", "खेजड़ी", "पीपल", "बड़"],
        1,
        "खेजड़ी (Prosopis cineraria) राज्य वृक्ष है। रोहिड़ा राज्य पुष्प है। खेजड़ी को रेगिस्तान का कल्पवृक्ष भी कहा जाता है।",
    ),
    Q(
        "राजस्थान का राज्य पुष्प कौन सा है?",
        ["कमल", "गुलाब", "रोहिड़ा", "गेंदा"],
        2,
        "रोहिड़ा (Tecomella undulata) राजस्थान का राज्य पुष्प है। मरुस्थलीय क्षेत्र में इसके पीले-नारंगी फूल दिखते हैं।",
    ),
    Q(
        "गुलाबी नगरी किसे कहा जाता है?",
        ["जोधपुर", "उदयपुर", "जयपुर", "बीकानेर"],
        2,
        "जयपुर को गुलाबी नगरी कहते हैं। जोधपुर नीली नगरी, उदयपुर झीलों की नगरी और जैसलमेर स्वर्ण नगरी कहलाती है।",
    ),
    Q(
        "झीलों की नगरी किसे कहते हैं?",
        ["अजमेर", "उदयपुर", "कोटा", "बूँदी"],
        1,
        "उदयपुर को झीलों की नगरी कहा जाता है। पिछोला, फतेहसागर और उदयसागर यहाँ की प्रसिद्ध झीलें हैं।",
    ),
    Q(
        "हल्दीघाटी का युद्ध किस वर्ष हुआ?",
        ["1527", "1556", "1576", "1707"],
        2,
        "हल्दीघाटी का युद्ध 18 जून 1576 को महाराणा प्रताप और अकबर की सेना (मान सिंह) के बीच हुआ। खानवा 1527 में राणा सांगा और बाबर के बीच हुआ था।",
        topic="itihas",
        tags=["itihas", "rajasthan gk"],
        difficulty="easy",
    ),
    Q(
        "खानवा का युद्ध किसके बीच हुआ?",
        ["राणा सांगा और बाबर", "महाराणा प्रताप और अकबर", "शिवाजी और औरंगज़ेब", "टीपू सुल्तान और अंग्रेज़"],
        0,
        "खानवा का युद्ध 1527 में राणा सांगा और बाबर के बीच हुआ। इसमें बाबर की विजय हुई।",
        topic="itihas",
        tags=["itihas", "rajasthan gk"],
        difficulty="medium",
    ),
    Q(
        "राजस्थान के प्रथम मुख्यमंत्री कौन थे?",
        ["मोहनलाल सुखाड़िया", "हीरालाल शास्त्री", "टीकाराम पालीवाल", "बरकतुल्लाह खान"],
        1,
        "हीरालाल शास्त्री वृहत्तर राजस्थान के प्रथम मुख्यमंत्री थे। मोहनलाल सुखाड़िया बाद में लंबे समय तक मुख्यमंत्री रहे।",
        topic="pol",
        tags=["pol", "rajasthan gk", "itihas"],
        difficulty="medium",
    ),
    Q(
        "लूनी नदी का उद्गम कहाँ से होता है?",
        ["जनापाव पहाड़ी, महू", "नाग पहाड़, अजमेर", "गुरु शिखर", "पुष्कर झील"],
        1,
        "लूनी नाग पहाड़ (अजमेर के पास) से निकलती है और कच्छ के रन की ओर जाती है। चंबल का उद्गम मध्य प्रदेश की जनापाव पहाड़ी से होता है।",
        topic="geo",
        tags=["geo", "rajasthan gk"],
        difficulty="medium",
    ),
    Q(
        "चंबल नदी का उद्गम कहाँ है?",
        ["नाग पहाड़, अजमेर", "जनापाव पहाड़ी, महू (मध्य प्रदेश)", "आबू पर्वत", "खेटड़ी"],
        1,
        "चंबल जनापाव पहाड़ी (महू, मध्य प्रदेश) से निकलती है। यह यमुना की सहायक है और राजस्थान की बड़ी नदी मानी जाती है, हालांकि उद्गम राजस्थान में नहीं है।",
        topic="geo",
        tags=["geo", "rajasthan gk"],
        difficulty="medium",
    ),
    Q(
        "राजस्थान की कौन सी नदी अक्सर 'मृत नदी' कही जाती है?",
        ["लूनी", "चंबल", "घग्गर", "बनास"],
        2,
        "घग्गर को अक्सर मृत नदी कहा जाता है। यह मौसमी नदी है और हड़प्पाकालीन सरस्वती से जोड़ी जाती रही है। अगर प्रश्न मत्स्य संघ का हो तो वह 18 मार्च 1948 का संघ है।",
        topic="geo",
        tags=["geo", "rajasthan gk"],
        difficulty="medium",
    ),
    Q(
        "अरावली का सर्वोच्च शिखर कौन सा है?",
        ["माउंट आबू", "गुरु शिखर", "देलवाड़ा", "काला पहाड़"],
        1,
        "गुरु शिखर (सिरोही) अरावली का सर्वोच्च शिखर है। ऊँचाई लगभग 1722 मीटर मानी जाती है। यह माउंट आबू क्षेत्र में है।",
        topic="geo",
        tags=["geo", "rajasthan gk"],
    ),
    Q(
        "रणथंभौर राष्ट्रीय उद्यान किस जिले में है?",
        ["भरतपुर", "सवाई माधोपुर", "कोटा", "अलवर"],
        1,
        "रणथंभौर सवाई माधोपुर में है। केवलादेव (घना) भरतपुर में और सरिस्का अलवर में है।",
        topic="geo",
        tags=["geo", "rajasthan gk"],
    ),
    Q(
        "राजस्थान विधानसभा में कुल कितनी सीटें हैं?",
        ["150", "175", "200", "225"],
        2,
        "राजस्थान विधानसभा में 200 सीटें हैं। लोकसभा में राज्य की 25 और राज्यसभा में 10 सीटें हैं।",
        topic="pol",
        tags=["pol", "rajasthan gk"],
    ),
    Q(
        "राजस्थान से लोकसभा की कितनी सीटें हैं?",
        ["20", "25", "28", "10"],
        1,
        "राजस्थान की लोकसभा सीटें 25 हैं। राज्यसभा सीटें 10 हैं। इन्हें विधानसभा की 200 सीटों से अलग याद रखें।",
        topic="pol",
        tags=["pol", "rajasthan gk"],
    ),
    Q(
        "राजस्थान उच्च न्यायालय कहाँ स्थित है?",
        ["केवल जयपुर", "जोधपुर, खंडपीठ जयपुर", "केवल अजमेर", "बीकानेर"],
        1,
        "राजस्थान उच्च न्यायालय का मुख्य स्थान जोधपुर है और जयपुर में खंडपीठ है।",
        topic="pol",
        tags=["pol", "rajasthan gk"],
        difficulty="easy",
    ),
    Q(
        "खेतड़ी किस खनिज के लिए प्रसिद्ध है?",
        ["सोना", "ताँबा", "जस्ता", "अभ्रक"],
        1,
        "खेतड़ी (झुंझुनू) ताँबे के लिए प्रसिद्ध है। मकराना संगमरमर के लिए और जावर जस्ते-सीसे के लिए जाना जाता है।",
        topic="geo",
        tags=["geo", "rajasthan gk"],
        difficulty="medium",
    ),
    Q(
        "भारत का प्रथम भूमिगत परमाणु परीक्षण कहाँ हुआ?",
        ["जैसलमेर — पोकरण", "बाड़मेर", "बीकानेर", "श्रीहरिकोटा"],
        0,
        "पोकरण (जैसलमेर) में 18 मई 1974 को प्रथम परीक्षण (स्माइलिंग बुद्ध) और मई 1998 में पोकरण-द्वितीय हुआ।",
        topic="itihas",
        tags=["itihas", "rajasthan gk"],
        difficulty="easy",
    ),
    Q(
        "केवलादेव राष्ट्रीय उद्यान किस लिए प्रसिद्ध है और कहाँ है?",
        ["बाघ, सवाई माधोपुर", "पक्षी, भरतपुर", "शेर, अलवर", "मगरमच्छ, कोटा"],
        1,
        "केवलादेव (घना) भरतपुर में है और पक्षी अभयारण्य के रूप में UNESCO सूची में है। रणथंभौर बाघों के लिए सवाई माधोपुर में है।",
        topic="geo",
        tags=["geo", "rajasthan gk"],
        difficulty="medium",
    ),
    Q(
        "RTE अधिनियम किस वर्ष पारित हुआ?",
        ["2002", "2005", "2009", "2020"],
        2,
        "निःशुल्क और अनिवार्य बाल शिक्षा का अधिकार अधिनियम 2009 है। यह 6 से 14 वर्ष के बच्चों से जुड़ा है। NEP 2020 अलग दस्तावेज़ है।",
        topic="cdp",
        tags=["cdp", "reet", "pol"],
        difficulty="easy",
    ),
    Q(
        "NEP 2020 के अनुसार फाउंडेशनल स्टेज की आयु क्या है?",
        ["6–14 वर्ष", "3–8 वर्ष", "11–14 वर्ष", "14–18 वर्ष"],
        1,
        "राष्ट्रीय शिक्षा नीति 2020 में फाउंडेशनल स्टेज 5 वर्ष का है, आयु 3 से 8 वर्ष (3 वर्ष प्री-स्कूल + कक्षा 1–2)।",
        topic="cdp",
        tags=["cdp", "reet"],
        difficulty="medium",
    ),
    Q(
        "'विद्यालय' शब्द में कौन-सी सन्धि है?",
        ["गुण सन्धि", "दीर्घ सन्धि", "वृद्धि सन्धि", "यण सन्धि"],
        1,
        "विद्या + आलय = विद्यालय। अ + आ = आ, यह दीर्घ सन्धि है।",
        topic="sanskrit",
        tags=["sanskrit", "hindi", "reet"],
        difficulty="medium",
    ),
    Q(
        "अ + इ मिलकर ए बनना कौन-सी सन्धि है? उदाहरण: नर + इंद्र = नरेन्द्र।",
        ["दीर्घ सन्धि", "गुण सन्धि", "वृद्धि सन्धि", "अयादि सन्धि"],
        1,
        "अ/आ + इ/ई = ए, यह गुण सन्धि है। नर + इंद्र = नरेन्द्र। दीर्घ में समान स्वर जुड़ते हैं, जैसे अ + आ = आ (विद्यालय)।",
        topic="sanskrit",
        tags=["sanskrit", "hindi"],
        difficulty="medium",
    ),
    Q(
        "CPU का पूर्ण रूप क्या है?",
        ["Central Program Unit", "Central Processing Unit", "Computer Personal Unit", "Control Processing Utility"],
        1,
        "CPU = Central Processing Unit। यह कम्प्यूटर का वह भाग है जो निर्देशों को प्रोसेस करता है।",
        topic="computer",
        tags=["computer", "rajasthan gk"],
        difficulty="easy",
    ),
    Q(
        "श्रृंखला 3, 6, 12, 24, ? में अगली संख्या क्या होगी?",
        ["30", "36", "48", "42"],
        2,
        "हर संख्या पिछली की दोगुनी है: 3×2=6, 6×2=12, 12×2=24, 24×2=48।",
        topic="reasoning",
        tags=["reasoning"],
        difficulty="easy",
    ),
    Q(
        "RAM का पूर्ण रूप क्या है?",
        ["Read Access Memory", "Random Access Memory", "Run All Memory", "Rapid Action Module"],
        1,
        "RAM = Random Access Memory। यह अस्थायी कार्य-स्मृति है, बिजली जाते ही सामान्यतः खाली हो जाती है।",
        topic="computer",
        tags=["computer"],
        difficulty="easy",
    ),
    Q(
        "अरावली पर्वत श्रेणी की सामान्य दिशा क्या है?",
        ["उत्तर से दक्षिण", "पूर्व से पश्चिम", "दक्षिण-पश्चिम से उत्तर-पूर्व", "पश्चिम से दक्षिण"],
        2,
        "अरावली दक्षिण-पश्चिम से उत्तर-पूर्व दिशा में फैली है। यह राजस्थान को पश्चिमी मरुस्थलीय और पूर्वी मैदानी भाग में बाँटने में भूमिका निभाती है।",
        topic="geo",
        tags=["geo", "rajasthan gk"],
        difficulty="medium",
    ),
    Q(
        "गोगाजी को मुख्यतः किस रूप में पूजा जाता है?",
        ["वर्षा के देवता", "नाग-रक्षक लोकदेवता", "केवल युद्ध-देवता", "नगर-स्थापना के देवता"],
        1,
        "गोगाजी (जाहर पीर) को सर्प-रक्षा से जुड़ा लोकदेवता माना जाता है। तेजाजी घोड़ों/पशुओं के रक्षक लोकदेवता के रूप में पूजे जाते हैं।",
        topic="itihas",
        tags=["itihas", "rajasthan gk"],
        difficulty="hard",
    ),
    Q(
        "कालबेलिया किससे जुड़ा लोकनृत्य है?",
        ["केवल फसल कटाई", "सपेरा समुदाय", "केवल दरबारी नृत्य", "केवल युद्ध नृत्य"],
        1,
        "कालबेलिया सपेरा समुदाय का नृत्य है और UNESCO की अमूर्त विरासत सूची में शामिल रहा है। घूमर राजस्थान का व्यापक रूप से जाना जाने वाला लोकनृत्य है।",
        tags=["rajasthan gk", "itihas"],
        difficulty="medium",
    ),
]
